stages:
  - test
  - build

test:
  stage: test
  image: golang:latest
  script: 
    - go test ./...

build:
  stage: build
  image: golang:latest
  before_script:
  script: 
    # Compile and name the binary as `hello-go`
    - go build -o hello-go
    # Execute the binary

docker:
  stage: build
  image: docker:17.07.0-ce
  script:
    - docker build .
